/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Crud.CompraCRUD;
import Crud.ItemCompraCRUD;
import Crud.ProdutoCRUD;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author LUANA
 */
public class Ge_BD extends javax.swing.JFrame {

    /**
     * Creates new form Ge_BD
     */
    public Ge_BD() {
        this.getContentPane().setBackground(new Color(209, 209, 209));
        initComponents();
        attDados();
    }
    
    public void attDados() {
        CompraCRUD comp = new CompraCRUD();
        int tComp = comp.getQuantDados();
        String qtC = Integer.toString(tComp);
        jTextFieldVend.setText(qtC);
        
        ItemCompraCRUD item = new ItemCompraCRUD();
        int tIt = item.getQuantDados();
        String qtIt = Integer.toString(tIt);
        jTextFieldItem.setText(qtIt);
        
        int tEst = item.getQuantDadosEstats();
        String qtEstat = Integer.toString(tEst);
        jTextFieldEstats.setText(qtEstat);
        
        ProdutoCRUD prod = new ProdutoCRUD();
        int tProd = prod.getQuantDados();
        String qtProd = Integer.toString(tProd);
        jTextFieldProd.setText(qtProd);
        
        int total = tComp + tIt + tEst + tProd;
        String qTotal = Integer.toString(total);
        jTextFieldTotal.setText(qTotal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldProd = new javax.swing.JTextField();
        jTextFieldEstats = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldItem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldVend = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonResetVendas = new javax.swing.JButton();
        jButtonResetProd = new javax.swing.JButton();
        jButtonResetAll = new javax.swing.JButton();
        jButtonResetItem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Banco de Dados");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(209, 209, 209));

        jTextFieldProd.setEditable(false);
        jTextFieldProd.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jTextFieldEstats.setEditable(false);
        jTextFieldEstats.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("Dados Gravados em Estatisticas:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("Dados Gravados em Itens por Venda:");

        jTextFieldItem.setEditable(false);
        jTextFieldItem.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText("Dados Gravados em Produtos:");

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Dados Gravados em Vendas:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setText("Total de Dados Gravados:");

        jTextFieldVend.setEditable(false);
        jTextFieldVend.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEstats, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProd, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVend, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEstats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        jPanel2.setBackground(new java.awt.Color(209, 209, 209));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonResetVendas.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButtonResetVendas.setText("Resetar Vendas");
        jButtonResetVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetVendasActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonResetVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jButtonResetProd.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButtonResetProd.setText("Resetar Produtos");
        jButtonResetProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetProdActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonResetProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jButtonResetAll.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButtonResetAll.setText("Resetar Tudo");
        jButtonResetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetAllActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonResetAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jButtonResetItem.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButtonResetItem.setText("Resetar Itens/Venda");
        jButtonResetItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetItemActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonResetItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 11, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Atenção! Ao resetar qualquer tabela, as estatisticas poderão ser afetadas!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonResetVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetVendasActionPerformed
        // TODO add your handling code here:
        CompraCRUD comp = new CompraCRUD();
        
        int r = JOptionPane.showConfirmDialog(null, "Cuidado! Você está prestes a resetar\n "
                + "a tabela de vendas!\n Continuar?", "Confirmar", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if(r == JOptionPane.YES_OPTION) {
            comp.resetar();
            JOptionPane.showMessageDialog(null, "Tabela Resetada com Sucesso!");
        }
        attDados();
    }//GEN-LAST:event_jButtonResetVendasActionPerformed

    private void jButtonResetProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetProdActionPerformed
        // TODO add your handling code here:
        ProdutoCRUD prod = new ProdutoCRUD();
        
        int r = JOptionPane.showConfirmDialog(null, "Cuidado! Você está prestes a resetar\n "
                + "a tabela de Produtos!\n Deseja Continuar?", "Confirmar", 
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if(r == JOptionPane.YES_OPTION) {
            prod.resetar();
            JOptionPane.showMessageDialog(null, "Tabela Resetada com Sucesso!");
        }
        
        attDados();
    }//GEN-LAST:event_jButtonResetProdActionPerformed

    private void jButtonResetItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetItemActionPerformed
        // TODO add your handling code here:
        ItemCompraCRUD item =  new ItemCompraCRUD();
        
        int r = JOptionPane.showConfirmDialog(null, "Cuidado! Você está prestes a resetar\n "
                + "a tabela de Itens!\n Deseja Continuar?", "Confirmar", 
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if(r == JOptionPane.YES_OPTION) {
            item.resetar();
            JOptionPane.showMessageDialog(null, "Tabela Resetada com Sucesso!");
        }
        attDados();
    }//GEN-LAST:event_jButtonResetItemActionPerformed

    private void jButtonResetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetAllActionPerformed
        // TODO add your handling code here:
        CompraCRUD comp = new CompraCRUD();
        ProdutoCRUD prod = new ProdutoCRUD();
        ItemCompraCRUD item =  new ItemCompraCRUD();
        
        int r = JOptionPane.showConfirmDialog(null, "Cuidado! Você está prestes a resetar\n "
                + "os dados de todas as tabelas!\n Essa ação não poderá ser revertida.\n "
                + "Deseja Continuar?", "Confirmar", 
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if(r == JOptionPane.YES_OPTION) {
            comp.resetar();
            prod.resetar();
            item.resetar();
            JOptionPane.showMessageDialog(null, "Todas as tabelas foram resetadas com sucesso!");
        }
        attDados();
    }//GEN-LAST:event_jButtonResetAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonResetAll;
    private javax.swing.JButton jButtonResetItem;
    private javax.swing.JButton jButtonResetProd;
    private javax.swing.JButton jButtonResetVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldEstats;
    private javax.swing.JTextField jTextFieldItem;
    private javax.swing.JTextField jTextFieldProd;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldVend;
    // End of variables declaration//GEN-END:variables
}
