package Interface;

import Classes.Produto;
import Crud.ProdutoCRUD;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class Gerenciamento extends javax.swing.JFrame {

    /**
     * Creates new form AplicTest
     */
    
    
    public Gerenciamento() {
        initComponents();
        this.getContentPane().setBackground(new Color(209, 209, 209));
        DefaultTableModel modelo = (DefaultTableModel) tableProd.getModel();
        tableProd.setRowSorter(new TableRowSorter(modelo));
        try{
            readJTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar tabela!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) tableProd.getModel();
        modelo.setNumRows(0);
        
        ProdutoCRUD crd = new ProdutoCRUD();
        
        for(Produto p: crd.read()) {
            
            modelo.addRow(new Object[]{
                p.getCod(),
                p.getDesc(),
                p.getQuant(),
                p.getUnidade(),
                p.getPrecAtac()
            });
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelStatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtProdName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxUnidade = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtProdQuant = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtProdPrec = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldEditDesc = new javax.swing.JTextField();
        jButtonEditDone = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxUnidadeEdit = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEditQuant = new javax.swing.JTextField();
        jLabelProduto = new javax.swing.JLabel();
        jButtonRemover = new javax.swing.JButton();
        jLabelCodProd = new javax.swing.JLabel();
        jButtonEditCancel = new javax.swing.JButton();
        jTextFieldEditPrec = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProd = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Produtos");
        setBackground(new java.awt.Color(0, 159, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(759, 560));
        setName("produtosAdd"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(209, 209, 209));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Gerenciamento de Produtos em Estoque");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel2.setBackground(new java.awt.Color(209, 209, 209));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 200));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Quantidade");
        jLabel3.setAutoscrolls(true);
        jLabel3.setMaximumSize(null);
        jLabel3.setMinimumSize(null);

        txtProdName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtProdName.setBorder(null);
        txtProdName.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtProdName.setMaximumSize(null);
        txtProdName.setMinimumSize(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Preço de Atacado");
        jLabel4.setAutoscrolls(true);
        jLabel4.setMaximumSize(null);
        jLabel4.setMinimumSize(null);

        jComboBoxUnidade.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jComboBoxUnidade.setMaximumRowCount(2);
        jComboBoxUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Unitário" }));
        jComboBoxUnidade.setToolTipText("");
        jComboBoxUnidade.setAutoscrolls(true);
        jComboBoxUnidade.setBorder(null);
        jComboBoxUnidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBoxUnidade.setMaximumSize(null);
        jComboBoxUnidade.setMinimumSize(null);
        jComboBoxUnidade.setPreferredSize(new java.awt.Dimension(69, 18));
        jComboBoxUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUnidadeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nome");
        jLabel2.setAutoscrolls(true);
        jLabel2.setMaximumSize(null);
        jLabel2.setMinimumSize(null);

        txtProdQuant.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtProdQuant.setBorder(null);
        txtProdQuant.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtProdQuant.setMaximumSize(null);
        txtProdQuant.setMinimumSize(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Unidade");
        jLabel8.setAutoscrolls(true);
        jLabel8.setMaximumSize(null);
        jLabel8.setMinimumSize(null);

        txtProdPrec.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtProdPrec.setBorder(null);
        txtProdPrec.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtProdPrec.setMaximumSize(null);
        txtProdPrec.setMinimumSize(null);

        jButtonAdd.setBackground(new java.awt.Color(51, 153, 0));
        jButtonAdd.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonAdd.setText("Adicionar");
        jButtonAdd.setAutoscrolls(true);
        jButtonAdd.setBorderPainted(false);
        jButtonAdd.setMaximumSize(null);
        jButtonAdd.setMinimumSize(null);
        jButtonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAddMouseExited(evt);
            }
        });
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtProdName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(53, 53, 53)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtProdQuant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBoxUnidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(125, 125, 125)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtProdPrec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBoxUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtProdPrec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProdName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtProdQuant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(39, 39, 39)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(209, 209, 209));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Unidade");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 172, -1, -1));

        jTextFieldEditDesc.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldEditDesc.setBorder(null);
        jTextFieldEditDesc.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldEditDesc.setEnabled(false);
        jPanel3.add(jTextFieldEditDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 71, -1));

        jButtonEditDone.setBackground(new java.awt.Color(51, 153, 0));
        jButtonEditDone.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonEditDone.setText("Concluido");
        jButtonEditDone.setBorderPainted(false);
        jButtonEditDone.setEnabled(false);
        jButtonEditDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEditDoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEditDoneMouseExited(evt);
            }
        });
        jButtonEditDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditDoneActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEditDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 217, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Quantidade");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 129, -1, -1));

        jComboBoxUnidadeEdit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jComboBoxUnidadeEdit.setMaximumRowCount(2);
        jComboBoxUnidadeEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Unitário" }));
        jComboBoxUnidadeEdit.setBorder(null);
        jComboBoxUnidadeEdit.setEnabled(false);
        jComboBoxUnidadeEdit.setPreferredSize(new java.awt.Dimension(69, 18));
        jComboBoxUnidadeEdit.setRequestFocusEnabled(false);
        jPanel3.add(jComboBoxUnidadeEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 194, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Preço R$");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 172, -1, -1));

        jButtonEdit.setBackground(new java.awt.Color(51, 153, 0));
        jButtonEdit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonEdit.setText("Editar Produto");
        jButtonEdit.setBorderPainted(false);
        jButtonEdit.setEnabled(false);
        jButtonEdit.setMaximumSize(new java.awt.Dimension(120, 36));
        jButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEditMouseExited(evt);
            }
        });
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Desc.");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, -1, -1));

        jTextFieldEditQuant.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldEditQuant.setBorder(null);
        jTextFieldEditQuant.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldEditQuant.setEnabled(false);
        jPanel3.add(jTextFieldEditQuant, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 150, 71, -1));

        jLabelProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelProduto.setText("Produto:");
        jPanel3.add(jLabelProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 11, -1, -1));

        jButtonRemover.setBackground(new java.awt.Color(51, 153, 0));
        jButtonRemover.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonRemover.setText("Remover Produto");
        jButtonRemover.setBorderPainted(false);
        jButtonRemover.setEnabled(false);
        jButtonRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRemoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRemoverMouseExited(evt);
            }
        });
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        jLabelCodProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCodProd.setText("Código:");
        jPanel3.add(jLabelCodProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 33, -1, -1));

        jButtonEditCancel.setBackground(new java.awt.Color(51, 153, 0));
        jButtonEditCancel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonEditCancel.setText("Cancelar");
        jButtonEditCancel.setBorderPainted(false);
        jButtonEditCancel.setEnabled(false);
        jButtonEditCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEditCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEditCancelMouseExited(evt);
            }
        });
        jButtonEditCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEditCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 217, -1, -1));

        jTextFieldEditPrec.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldEditPrec.setBorder(null);
        jTextFieldEditPrec.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldEditPrec.setEnabled(false);
        jPanel3.add(jTextFieldEditPrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, 71, -1));

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setBorder(null);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setDoubleBuffered(true);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusCycleRoot(true);

        tableProd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Desc.", "Quant.", "Unidade", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProd.setGridColor(new java.awt.Color(204, 204, 204));
        tableProd.setSelectionBackground(new java.awt.Color(51, 153, 0));
        tableProd.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableProd.getTableHeader().setReorderingAllowed(false);
        tableProd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tableProdFocusLost(evt);
            }
        });
        tableProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProd);
        if (tableProd.getColumnModel().getColumnCount() > 0) {
            tableProd.getColumnModel().getColumn(0).setMinWidth(25);
            tableProd.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableProd.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel6.add(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleName("Produtos");
        getAccessibleContext().setAccessibleDescription("Adicionar e Remover Produtos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        
        Produto p = new Produto();
        ProdutoCRUD crd = new ProdutoCRUD();
        
        if(txtProdName.getText().equals("") || txtProdQuant.getText().equals("") || txtProdPrec.getText().equals("")) {
            jLabelStatus.setForeground(Color.red);
            jLabelStatus.setText("Preencha todos os campos!");
        } else if (!(txtProdName.getText().equals("") || txtProdQuant.getText().equals("") || txtProdPrec.getText().equals(""))){
            p.setDesc(txtProdName.getText());
            p.setQuant(Double.parseDouble(txtProdQuant.getText()));
            if(jComboBoxUnidade.getSelectedItem().toString().equalsIgnoreCase("Kg")) {
                p.setUnidade("Kg");
            } else if(jComboBoxUnidade.getSelectedItem().toString().equalsIgnoreCase("Unitário")) {
                p.setUnidade("Un");
            }
            p.setPrecAtac(Double.parseDouble(txtProdPrec.getText()));
            
            crd.add(p);
            
            txtProdName.setText("");
            txtProdQuant.setText("");
            txtProdPrec.setText("");
            jLabelStatus.setForeground(Color.green);
            jLabelStatus.setText("Produto adicionado com sucesso!");
        }
        
        readJTable();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        // TODO add your handling code here:
        ProdutoCRUD crd = new ProdutoCRUD();       
        int col = tableProd.getSelectedRow();
        int codProd = (int) tableProd.getValueAt(col, 0);
        
        if(crd.remover(codProd) == 1) {
            jLabelStatus.setForeground(Color.green);
            jLabelStatus.setText("Produto Removido com Sucesso!");
        } else if (crd.remover(codProd) == 2) {
            jLabelStatus.setForeground(Color.red);
            jLabelStatus.setText("Erro ao Remover Produto");
        }
        
        readJTable();
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void tableProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdMouseClicked
        // TODO add your handling code here:
        int col = tableProd.getSelectedRow();
        int codProd = (int) tableProd.getValueAt(col, 0);
        String  prod = (String) tableProd.getValueAt(col, 1);
        double quant = (double) tableProd.getValueAt(col, 2);
        String unidade = (String) tableProd.getValueAt(col, 3);
        double prec = (double) tableProd.getValueAt(col, 4);
        jLabelProduto.setText("Produto: " + prod);
        jLabelCodProd.setText("Código: " + codProd);
        jTextFieldEditDesc.setText(prod);
        jTextFieldEditQuant.setText(Double.toString(quant));
        jTextFieldEditPrec.setText(Double.toString(prec));
        if(unidade.equalsIgnoreCase("Kg")) {
            jComboBoxUnidadeEdit.setSelectedIndex(0);
        } else if(unidade.equalsIgnoreCase("Un")) {
            jComboBoxUnidadeEdit.setSelectedIndex(1);
        }

        jButtonRemover.setEnabled(true);
        jButtonEdit.setEnabled(true);
      
    }//GEN-LAST:event_tableProdMouseClicked

    private void tableProdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableProdFocusLost
        // TODO add your handling code here:
        //jLabelProduto.setText("Produto: ");
        //jLabelCodProd.setText("Código: ");
    }//GEN-LAST:event_tableProdFocusLost

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        jTextFieldEditDesc.setEnabled(true);
        jTextFieldEditQuant.setEnabled(true);
        jTextFieldEditPrec.setEnabled(true);
        jButtonEditDone.setEnabled(true);
        jButtonEditCancel.setEnabled(true);
        jComboBoxUnidadeEdit.setEnabled(true);
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonEditDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditDoneActionPerformed
        // TODO add your handling code here:
        ProdutoCRUD crd = new ProdutoCRUD();
        int col = tableProd.getSelectedRow();
        int codProd = (int) tableProd.getValueAt(col, 0);
        String descProd = jTextFieldEditDesc.getText();
        double quantProd = Double.parseDouble(jTextFieldEditQuant.getText());
        String unidade = jComboBoxUnidadeEdit.getSelectedItem().toString();
        double precProd = Double.parseDouble(jTextFieldEditPrec.getText());
        
        if(unidade.equalsIgnoreCase("Unitário")) {
            unidade = "Un";
        }
        
        if(crd.editar(codProd, descProd, quantProd,unidade, precProd) == 1) {
            jLabelStatus.setForeground(Color.BLUE);
            jLabelStatus.setText("Produto Editado Com Sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao editar Produto!");
            jLabelStatus.setText("");
        }
        jTextFieldEditDesc.setEnabled(false);
        jTextFieldEditQuant.setEnabled(false);
        jTextFieldEditPrec.setEnabled(false);
        jButtonEditDone.setEnabled(false);
        jButtonEditCancel.setEnabled(false);
        jComboBoxUnidadeEdit.setEnabled(false);
        readJTable();
    }//GEN-LAST:event_jButtonEditDoneActionPerformed

    private void jButtonAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseEntered
        // TODO add your handling code here:
        jButtonAdd.setBackground(new Color(59, 178, 0));
    }//GEN-LAST:event_jButtonAddMouseEntered

    private void jButtonAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddMouseExited
        // TODO add your handling code here:
        jButtonAdd.setBackground(new Color(51, 153, 0));
    }//GEN-LAST:event_jButtonAddMouseExited

    private void jButtonRemoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoverMouseEntered
        // TODO add your handling code here:
        if(jButtonRemover.isEnabled()) {
            jButtonRemover.setBackground(new Color(59, 178, 0));
        }
    }//GEN-LAST:event_jButtonRemoverMouseEntered

    private void jButtonRemoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoverMouseExited
        // TODO add your handling code here:
        jButtonRemover.setBackground(new Color(51, 153, 0));
    }//GEN-LAST:event_jButtonRemoverMouseExited

    private void jButtonEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseEntered
        // TODO add your handling code here:
        if(jButtonEdit.isEnabled()) {
            jButtonEdit.setBackground(new Color(59, 178, 0)); 
        }
    }//GEN-LAST:event_jButtonEditMouseEntered

    private void jButtonEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseExited
        // TODO add your handling code here:
        jButtonEdit.setBackground(new Color(51, 153, 0));
    }//GEN-LAST:event_jButtonEditMouseExited

    private void jButtonEditDoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditDoneMouseEntered
        // TODO add your handling code here:
        if(jButtonEditDone.isEnabled()) {
            jButtonEditDone.setBackground(new Color(59, 178, 0));
        }
    }//GEN-LAST:event_jButtonEditDoneMouseEntered

    private void jButtonEditDoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditDoneMouseExited
        // TODO add your handling code here:
        jButtonEditDone.setBackground(new Color(51, 153, 0));
    }//GEN-LAST:event_jButtonEditDoneMouseExited

    private void jButtonEditCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditCancelMouseEntered
        // TODO add your handling code here:
        if(jButtonEditCancel.isEnabled()) {
            jButtonEditCancel.setBackground(new Color(59, 178, 0));
        }
    }//GEN-LAST:event_jButtonEditCancelMouseEntered

    private void jButtonEditCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditCancelMouseExited
        // TODO add your handling code here:
        jButtonEditCancel.setBackground(new Color(51, 153, 0));
    }//GEN-LAST:event_jButtonEditCancelMouseExited

    private void jButtonEditCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditCancelActionPerformed
        // TODO add your handling code here:
        int col = tableProd.getSelectedRow();
        String  prod = (String) tableProd.getValueAt(col, 1);
        double quant = (double) tableProd.getValueAt(col, 2);
        double prec = (double) tableProd.getValueAt(col, 4);
        jTextFieldEditDesc.setText(prod);
        jTextFieldEditQuant.setText(Double.toString(quant));
        jTextFieldEditPrec.setText(Double.toString(prec));
        
        jTextFieldEditDesc.setEnabled(false);
        jTextFieldEditQuant.setEnabled(false);
        jTextFieldEditPrec.setEnabled(false);
        jButtonEditDone.setEnabled(false);
        jButtonEditCancel.setEnabled(false);
        jComboBoxUnidadeEdit.setEnabled(false);
    }//GEN-LAST:event_jButtonEditCancelActionPerformed

    private void jComboBoxUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUnidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonEditCancel;
    private javax.swing.JButton jButtonEditDone;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JComboBox<String> jComboBoxUnidade;
    private javax.swing.JComboBox<String> jComboBoxUnidadeEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCodProd;
    private javax.swing.JLabel jLabelProduto;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldEditDesc;
    private javax.swing.JTextField jTextFieldEditPrec;
    private javax.swing.JTextField jTextFieldEditQuant;
    private javax.swing.JTable tableProd;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtProdPrec;
    private javax.swing.JTextField txtProdQuant;
    // End of variables declaration//GEN-END:variables
}
