package Interface;

import Classes.*;
import Crud.*;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class Real_Vendas extends javax.swing.JFrame {

    /**
     * Creates new form TestCompra
     */
    Date dataHj = new Date();
    SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    DecimalFormat dfn = new DecimalFormat("0.##");
    SimpleDateFormat hr = new SimpleDateFormat("HH:mm:ss");
    int codSelected;

    public Real_Vendas() {
        initComponents();
        this.getContentPane().setBackground(new Color(209, 209, 209));
        jTextData.setText(df.format(dataHj));
        DefaultTableModel modelo = (DefaultTableModel) jTableListaProd.getModel();
        jTableListaProd.setRowSorter(new TableRowSorter(modelo));
        
        try {
            readJTable();
        } catch (Exception e) {
            System.out.println("Erro ao atualizar tabela: " + e);
            JOptionPane.showMessageDialog(null, "Erro ao carregar tabela", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
     public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTableListaProd.getModel();
        modelo.setNumRows(0);
        
        ProdutoCRUD crd = new ProdutoCRUD();
        
        for(Produto p: crd.read()) {
            
            modelo.addRow(new Object[]{
                p.getCod(),
                p.getDesc(),
                p.getQuant(),
                p.getUnidade()
            });
            
        }
    }
     
     public void readJTableSearch(String desc) {
        DefaultTableModel modelo = (DefaultTableModel) jTableListaProd.getModel();
        modelo.setNumRows(0);
        
        ProdutoCRUD crd = new ProdutoCRUD();
        
        for(Produto p: crd.readDescProd(desc)) {
            
            modelo.addRow(new Object[]{
                p.getCod(),
                p.getDesc(),
                p.getQuant(),
                p.getUnidade()
            });   
        }
    }
    public void selectedProd() {
        int col = jTableListaProd.getSelectedRow();
        codSelected = (int) jTableListaProd.getValueAt(col, 0);
        String cod = Integer.toString(codSelected);
        jTextNomeProd.setText(cod + " " + String.valueOf(jTableListaProd.getValueAt(col, 1)));
        String unidP = (String) jTableListaProd.getValueAt(col, 3);
        jButtonAddLista.setEnabled(true);
        
         if(unidP.equalsIgnoreCase("Kg")) {
            jTextFieldQuantItem.setEnabled(true);
        } else {
            jTextFieldQuantItem.setEnabled(false);
            jTextFieldQuantItem.setText("1.00");
        }
    }
    
    public void readJTableLista(int codCompra) {
        ItemCompraCRUD itemCrd = new ItemCompraCRUD();
        
        DefaultTableModel modelo = (DefaultTableModel) jTableListaComp.getModel();
        modelo.setNumRows(0);
        
        double totalCompra = 0;
        for(ListaCompra lc : itemCrd.readListaCompra(codCompra)) {
            modelo.addRow(new Object[] {
                lc.getDescProd(),
                lc.getPrecProd(),
                lc.getQuantProd(),
                lc.getUnidProd(),
                lc.getCodItem()
            });
           totalCompra +=  lc.getPrecProd();
        }
        String totalCompraF = dfn.format(totalCompra);
        totalCompraF = totalCompraF.replace(",", ".");
       jTextFieldPrecTotal.setText(totalCompraF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldQuantItem = new javax.swing.JTextField();
        jTextNomeProd = new javax.swing.JTextField();
        jTextFieldPrecoItem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonAddLista = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaProd = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jTextSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JButtonSearch = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonRemovProdList = new javax.swing.JButton();
        jTextFieldCodigoCompra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldDin = new javax.swing.JFormattedTextField();
        jTextData = new javax.swing.JTextField();
        jRadioDin = new javax.swing.JRadioButton();
        jRadioCard = new javax.swing.JRadioButton();
        jButtonRealComp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxEditData = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jTextFieldPrecTotal = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTroco = new javax.swing.JFormattedTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListaComp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Janela Vendas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.gray);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(740, 461));
        setName("vendas"); // NOI18N

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));

        jPanel9.setBackground(new java.awt.Color(209, 209, 209));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Realização de Vendas");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 221, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(209, 209, 209));

        jTextFieldQuantItem.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldQuantItem.setText("0.00");
        jTextFieldQuantItem.setBorder(null);
        jTextFieldQuantItem.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldQuantItem.setEnabled(false);

        jTextNomeProd.setEditable(false);
        jTextNomeProd.setBackground(new java.awt.Color(255, 255, 255));
        jTextNomeProd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextNomeProd.setBorder(null);
        jTextNomeProd.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        jTextFieldPrecoItem.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldPrecoItem.setBorder(null);
        jTextFieldPrecoItem.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Peso:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Preço");

        jButtonAddLista.setBackground(new java.awt.Color(51, 153, 0));
        jButtonAddLista.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonAddLista.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddLista.setText("Adicionar na Lista");
        jButtonAddLista.setBorderPainted(false);
        jButtonAddLista.setEnabled(false);
        jButtonAddLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAddListaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAddListaMouseExited(evt);
            }
        });
        jButtonAddLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddListaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Produto: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddLista))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldQuantItem, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPrecoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextNomeProd))))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldPrecoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButtonAddLista))
        );

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jTableListaProd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTableListaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Descrição", "Quant. Estoq.", "Unidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaProd.setGridColor(new java.awt.Color(204, 204, 204));
        jTableListaProd.setSelectionBackground(new java.awt.Color(51, 153, 0));
        jTableListaProd.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableListaProd.getTableHeader().setReorderingAllowed(false);
        jTableListaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaProdMouseClicked(evt);
            }
        });
        jTableListaProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableListaProdKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaProd);
        if (jTableListaProd.getColumnModel().getColumnCount() > 0) {
            jTableListaProd.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableListaProd.getColumnModel().getColumn(1).setMinWidth(60);
            jTableListaProd.getColumnModel().getColumn(2).setMinWidth(40);
        }

        jPanel3.add(jScrollPane1);

        jPanel4.setBackground(new java.awt.Color(209, 209, 209));

        jTextSearch.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextSearch.setBorder(null);
        jTextSearch.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextSearch.setMinimumSize(new java.awt.Dimension(60, 16));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Buscar Item:");

        JButtonSearch.setBackground(new java.awt.Color(51, 153, 0));
        JButtonSearch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        JButtonSearch.setForeground(new java.awt.Color(255, 255, 255));
        JButtonSearch.setText("Buscar");
        JButtonSearch.setBorderPainted(false);
        JButtonSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JButtonSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JButtonSearchMouseExited(evt);
            }
        });
        JButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButtonSearch)
                .addGap(152, 152, 152))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        jPanel5.setBackground(new java.awt.Color(209, 209, 209));

        jButtonRemovProdList.setBackground(new java.awt.Color(51, 153, 0));
        jButtonRemovProdList.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonRemovProdList.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRemovProdList.setText("Remover Item ");
        jButtonRemovProdList.setBorderPainted(false);
        jButtonRemovProdList.setEnabled(false);
        jButtonRemovProdList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRemovProdListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRemovProdListMouseExited(evt);
            }
        });
        jButtonRemovProdList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemovProdListActionPerformed(evt);
            }
        });

        jTextFieldCodigoCompra.setEditable(false);
        jTextFieldCodigoCompra.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCodigoCompra.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldCodigoCompra.setBorder(null);
        jTextFieldCodigoCompra.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Lista de Compras:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Cód.:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCodigoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRemovProdList))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCodigoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemovProdList))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(209, 209, 209));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Dinheiro:");

        jTextFieldDin.setBorder(null);
        jTextFieldDin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jTextFieldDin.setText("0.00");
        jTextFieldDin.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldDin.setEnabled(false);
        jTextFieldDin.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldDin.setInheritsPopupMenu(true);
        jTextFieldDin.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldDinCaretUpdate(evt);
            }
        });

        jTextData.setEditable(false);
        jTextData.setBackground(new java.awt.Color(255, 255, 255));
        jTextData.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextData.setBorder(null);
        jTextData.setDisabledTextColor(new java.awt.Color(204, 204, 204));

        jRadioDin.setBackground(new java.awt.Color(209, 209, 209));
        buttonGroup1.add(jRadioDin);
        jRadioDin.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioDin.setText("Dinheiro");
        jRadioDin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioDinMouseClicked(evt);
            }
        });

        jRadioCard.setBackground(new java.awt.Color(209, 209, 209));
        buttonGroup1.add(jRadioCard);
        jRadioCard.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioCard.setSelected(true);
        jRadioCard.setText("Cartão");
        jRadioCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioCardMouseClicked(evt);
            }
        });

        jButtonRealComp.setBackground(new java.awt.Color(51, 153, 0));
        jButtonRealComp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonRealComp.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRealComp.setText("Concluido");
        jButtonRealComp.setBorderPainted(false);
        jButtonRealComp.setEnabled(false);
        jButtonRealComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRealCompMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRealCompMouseExited(evt);
            }
        });
        jButtonRealComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealCompActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Data da Compra:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Forma de Pagamento: ");

        jCheckBoxEditData.setBackground(new java.awt.Color(209, 209, 209));
        jCheckBoxEditData.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jCheckBoxEditData.setText("Editar Data");
        jCheckBoxEditData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEditDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextData, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxEditData, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDin))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioDin, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioCard, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(7, 7, 7)))
                .addGap(9, 9, 9))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRealComp, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioDin)
                    .addComponent(jRadioCard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldDin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxEditData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRealComp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(209, 209, 209));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel10.setBackground(new java.awt.Color(209, 209, 209));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldPrecTotal.setEditable(false);
        jTextFieldPrecTotal.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPrecTotal.setBorder(null);
        jTextFieldPrecTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0"))));
        jTextFieldPrecTotal.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldPrecTotal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel10.add(jTextFieldPrecTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 11, 68, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Valor Total:");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Troco:");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 50, -1));

        jTextFieldTroco.setEditable(false);
        jTextFieldTroco.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTroco.setBorder(null);
        jTextFieldTroco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jTextFieldTroco.setText("0.00");
        jTextFieldTroco.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldTroco.setEnabled(false);
        jTextFieldTroco.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel10.add(jTextFieldTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 45, 68, -1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jTableListaComp.setAutoCreateRowSorter(true);
        jTableListaComp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTableListaComp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Desc.", "Valor", "Quantidade", "Unidade", "nº Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaComp.setGridColor(new java.awt.Color(204, 204, 204));
        jTableListaComp.setSelectionBackground(new java.awt.Color(51, 153, 0));
        jTableListaComp.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableListaComp.getTableHeader().setReorderingAllowed(false);
        jTableListaComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaCompMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableListaComp);
        if (jTableListaComp.getColumnModel().getColumnCount() > 0) {
            jTableListaComp.getColumnModel().getColumn(0).setMinWidth(70);
            jTableListaComp.getColumnModel().getColumn(1).setMinWidth(50);
            jTableListaComp.getColumnModel().getColumn(2).setMinWidth(50);
        }

        jPanel8.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSearchActionPerformed
        // TODO add your handling code here:
        readJTableSearch(jTextSearch.getText());
    }//GEN-LAST:event_JButtonSearchActionPerformed

    private void jButtonAddListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddListaActionPerformed
        // TODO add your handling code here:
        CompraCRUD compraCrd = new CompraCRUD();
        int codCompra = compraCrd.readCompraAtual() + 1;
        jTextFieldCodigoCompra.setText(String.valueOf(codCompra));
        
        ItemCompra ic = new ItemCompra();
        ItemCompraCRUD itemCrd = new ItemCompraCRUD();
        int col = jTableListaProd.getSelectedRow();
        int codP = (int) jTableListaProd.getValueAt(col, 0);
        String unidP = (String) jTableListaProd.getValueAt(col, 3);
        //double precUn = (Double) jTableListaProd.getValueAt(col, 4);
        double quant = Double.parseDouble(jTextFieldQuantItem.getText());
        double precP = Double.parseDouble(jTextFieldPrecoItem.getText())*quant;
        String precPF = dfn.format(precP);
        precPF = precPF.replace(",", ".");
        
        ic.setCompra(codCompra);
        ic.setProduto(codP);
        ic.setQuantItem(quant);
        ic.setPrecTotal(Double.parseDouble(precPF));
        //ic.setPrecUnit(precUn);
        ic.setUnidade(unidP);
        
        itemCrd.add(ic);
        readJTableLista(codCompra);
        readJTable();
        jButtonRealComp.setEnabled(true); 
    }//GEN-LAST:event_jButtonAddListaActionPerformed

    private void jButtonRemovProdListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemovProdListActionPerformed
        // TODO add your handling code here:
        int col = jTableListaComp.getSelectedRow();
        int codItem = (int) jTableListaComp.getValueAt(col, 4);
        int codCompra = Integer.parseInt(jTextFieldCodigoCompra.getText());
        ItemCompraCRUD crd = new ItemCompraCRUD();
        
        crd.remover(codItem);
        readJTableLista(codCompra);
        
    }//GEN-LAST:event_jButtonRemovProdListActionPerformed

    private void jTableListaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaProdMouseClicked
        // TODO add your handling code here:
        selectedProd();
    }//GEN-LAST:event_jTableListaProdMouseClicked

    private void jTableListaProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableListaProdKeyReleased
        // TODO add your handling code here:
        selectedProd();
    }//GEN-LAST:event_jTableListaProdKeyReleased

    private void JButtonSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonSearchMouseEntered
        // TODO add your handling code here:
        JButtonSearch.setBackground(new Color(59, 178, 0));
    }//GEN-LAST:event_JButtonSearchMouseEntered

    private void JButtonSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonSearchMouseExited
        // TODO add your handling code here:
        JButtonSearch.setBackground(new Color(51, 153, 0));
    }//GEN-LAST:event_JButtonSearchMouseExited

    private void jButtonAddListaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddListaMouseEntered
        // TODO add your handling code here:
        if(jButtonAddLista.isEnabled()) {
           jButtonAddLista.setBackground(new Color(59, 178, 0));
        }
    }//GEN-LAST:event_jButtonAddListaMouseEntered

    private void jButtonAddListaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddListaMouseExited
        // TODO add your handling code here:
        jButtonAddLista.setBackground(new Color(51, 153, 0));
    }//GEN-LAST:event_jButtonAddListaMouseExited

    private void jTableListaCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaCompMouseClicked
        // TODO add your handling code here:
        jButtonRemovProdList.setEnabled(true);
    }//GEN-LAST:event_jTableListaCompMouseClicked

    private void jButtonRemovProdListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemovProdListMouseEntered
        // TODO add your handling code here:
        if(jButtonRemovProdList.isEnabled()) {
            jButtonRemovProdList.setBackground(new Color(59, 178, 0));
        }
    }//GEN-LAST:event_jButtonRemovProdListMouseEntered

    private void jButtonRemovProdListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemovProdListMouseExited
        // TODO add your handling code here:
        jButtonRemovProdList.setBackground(new Color(51, 153, 0));
    }//GEN-LAST:event_jButtonRemovProdListMouseExited

    private void jCheckBoxEditDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEditDataActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxEditData.isSelected()){
            jTextData.setEditable(true);
        } else {
            jTextData.setEditable(false);
            jTextData.setText(df.format(dataHj));
        }
    }//GEN-LAST:event_jCheckBoxEditDataActionPerformed

    private void jButtonRealCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealCompActionPerformed
        // TODO add your handling code here:
        Compra c = new Compra();
        CompraCRUD crd = new CompraCRUD();
        int codC = Integer.parseInt(jTextFieldCodigoCompra.getText());
        double vlrTot = Double.parseDouble(jTextFieldPrecTotal.getText());
        SimpleDateFormat dtSQL = new SimpleDateFormat("yyyy-MM-dd");
        String dataa = jTextData.getText();
        int d = Integer.parseInt(dataa.substring(0, 2));
        int m = Integer.parseInt(dataa.substring(3, 5)) - 1;
        int y = Integer.parseInt(dataa.substring(6, 10)) - 1900;
        Date dtCC = new Date(y, m, d);
        System.out.println(dtSQL.format(dtCC));
        String dtCom = (dtSQL.format(dtCC)) + " " + hr.format(dataHj);
        System.out.println(dtCom);

        if(jCheckBoxEditData.isSelected()) c.setData(dtCom);
        else c.setData("");

        if(jRadioDin.isSelected()) {
            c.setPagForm("Dinheiro");
        } else if(jRadioCard.isSelected()) {
            c.setPagForm("Cartão");
        }

        c.setCod(codC);
        c.setVlrTot(vlrTot);
        crd.add(c);

        DefaultTableModel modelo = (DefaultTableModel) jTableListaComp.getModel();
        modelo.setNumRows(0);
        jButtonRealComp.setEnabled(false);
        jButtonRemovProdList.setEnabled(false);
    }//GEN-LAST:event_jButtonRealCompActionPerformed

    private void jButtonRealCompMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRealCompMouseExited
        // TODO add your handling code here:
        jButtonRealComp.setBackground(new Color(51, 153, 0));
    }//GEN-LAST:event_jButtonRealCompMouseExited

    private void jButtonRealCompMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRealCompMouseEntered
        // TODO add your handling code here:
        if(jButtonRealComp.isEnabled()) {
            jButtonRealComp.setBackground(new Color(59, 178, 0));
        }
    }//GEN-LAST:event_jButtonRealCompMouseEntered

    private void jTextFieldDinCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldDinCaretUpdate
        // TODO add your handling code here:
        if(jRadioDin.isSelected()){
            if (!(jTextFieldDin.getText().isEmpty())) {
                double troco = (Double.parseDouble(jTextFieldDin.getText())) - (Double.parseDouble(jTextFieldPrecTotal.getText()));
                jTextFieldTroco.setText(String.valueOf(dfn.format(troco)));
            }
        }
    }//GEN-LAST:event_jTextFieldDinCaretUpdate

    private void jRadioCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioCardMouseClicked
        // TODO add your handling code here:
        if(jRadioCard.isSelected()){
            jTextFieldDin.setEnabled(false);
            jTextFieldDin.setText("0.00");
            jTextFieldTroco.setEnabled(false);
            jTextFieldTroco.setText("0.00");
        }
    }//GEN-LAST:event_jRadioCardMouseClicked

    private void jRadioDinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioDinMouseClicked
        // TODO add your handling code here:
        if(jRadioDin.isSelected()) {
            jTextFieldDin.setEnabled(true);
            jTextFieldTroco.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioDinMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAddLista;
    private javax.swing.JButton jButtonRealComp;
    private javax.swing.JButton jButtonRemovProdList;
    private javax.swing.JCheckBox jCheckBoxEditData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioCard;
    private javax.swing.JRadioButton jRadioDin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableListaComp;
    private javax.swing.JTable jTableListaProd;
    private javax.swing.JTextField jTextData;
    private javax.swing.JTextField jTextFieldCodigoCompra;
    private javax.swing.JFormattedTextField jTextFieldDin;
    private javax.swing.JFormattedTextField jTextFieldPrecTotal;
    private javax.swing.JTextField jTextFieldPrecoItem;
    private javax.swing.JTextField jTextFieldQuantItem;
    private javax.swing.JFormattedTextField jTextFieldTroco;
    private javax.swing.JTextField jTextNomeProd;
    private javax.swing.JTextField jTextSearch;
    // End of variables declaration//GEN-END:variables
}
